apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 5
  source:
    path: helms/grafana
    repoURL: https://github.com/AndreGirbal/VagrantLab.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - $values/helms/grafana/values.yaml
    - repoURL: 'https://github.com/AndreGirbal/VagrantLab.git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true