apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vulnapp-ingress
  namespace: vulnapp
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ingressClassName: nginx
  rules:
    - host: vulnapp.local.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vulnerableapp-facade
                port:
                  number: 80
